### ISSUE TITLE
reg-sub with single arity fns?

### ISSUE THREAD

**Issue by stoeckley** [lambdaisland/breakout#3]
Your reg-subs are fns of only one arity:

https://github.com/lambdaisland/breakout/blob/master/src/cljs/breakout/subs.cljs#L7

But according to this, single arity fns are not an option for reg-sub:

https://github.com/Day8/re-frame/blob/1710e86cedfe13ea14115577553df292e6fb0db9/src/re_frame/subs.cljc#L137

I suspect yours are working because Javascript tends to ignore function arities, so your functions are actually receiving but not using the second arg.

**Comment by plexus** [comment]
Hi @astoeckley, you're correct, In this case I didn't care about the subscription vector, and JavaScript will simply ignore the extra arguments, so it happens to work. I agree it's bad form, would be better to have a `_` argument so it's clear that it's ignored.
